spring.application.name=artesanias

# URL CORREGIDA - agregar allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://localhost:8080/artesaniasdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Milagros2442+
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (para mapear las entidades automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect